### ISSUE TITLE
I couldn't get the learn test or rspec to work

### ISSUE THREAD

**Issue by OneShepForward** [learn-co-curriculum/phase-3-debugging-with-pry#3]
### Canvas Link

https://learning.flatironschool.com/courses/4551/assignments/160860?module_item_id=344876

### Concern

oneshepforward@LAPTOP-NL2PKA70:~/Development/code/phase-3/phase-3-debugging-with-pry$ learn testTraceback (most recent call last):
        4: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        3: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
        2: from /usr/share/rvm/gems/ruby-2.7.4/bin/learn:25:in `<main>'
        1: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.2.28/lib/bundler/rubygems_integration.rb:392:in `block in replace_bin_path'
/usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.2.28/lib/bundler/rubygems_integration.rb:364:in `block in replace_bin_path': can't find executable learn for gem learn-co. learn-co is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
oneshepforward@LAPTOP-NL2PKA70:~/Development/code/phase-3/phase-3-debugging-with-pry$ rspec
Traceback (most recent call last):
        4: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        3: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
        2: from /usr/share/rvm/gems/ruby-2.7.4/bin/rspec:25:in `<main>'
        1: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.2.28/lib/bundler/rubygems_integration.rb:392:in `block in replace_bin_path'
/usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.2.28/lib/bundler/rubygems_integration.rb:364:in `block in replace_bin_path': can't find executable rspec for gem rspec-core. rspec-core is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

### Additional Context

I'm not sure why, but the tests wouldn't work for me. I tried cloning again, but no joy.

**Comment by OneShepForward** [comment]
Oops! I rearranged my Development/Code subfolders into different phases yesterday and botched my learn gem. Got it sorted now. Sorry for the false alarm!
